### ISSUE TITLE
Please upgrade your plugin to support IDEA 2022.1

### ISSUE THREAD

**Issue by Greenplumwine** [pg-liudong/mybatis-log-plus-usage#3]
Hello developer, your plugin is really nice. But recently encountered a problem. After IDEA is upgraded to 2022.1, your plug-in can no longer be used. Please update the supported version in time, or open source your version, so that we can help you fix the problem of the plug-in together. Hope you can take this suggestion

**Comment by pg-liudong** [comment]
Thank you for your suggestion. The plug-in supports version 2022.1. The plug-in market is under review. Or go to the home page to download the corresponding version and install it offline!
